-- Run as the schema user exposed through ORDS.
-- SQL*Plus, SQLcl, and Oracle Database Actions recognize `/` as a block terminator.

begin
  execute immediate '
    create table keepalive_log (
      id number generated by default as identity primary key,
      ping_time timestamp with time zone default systimestamp not null,
      status varchar2(32 char) not null,
      colo varchar2(8 char),
      country varchar2(2 char),
      city varchar2(128 char),
      region varchar2(128 char),
      ip varchar2(45 char)
    )';
exception
  when others then
    if sqlcode != -955 then
      raise;
    end if;
end;
/

begin
  execute immediate '
    create index keepalive_log_ping_time_idx
    on keepalive_log (ping_time desc)';
exception
  when others then
    if sqlcode != -955 then
      raise;
    end if;
end;
/
