-- Run in the Supabase SQL editor as a project administrator.
-- The Worker uses a server-side secret key and does not expose these tables.

create table if not exists public.my_keepalive_logs (
  id bigint generated by default as identity primary key,
  ping_time timestamptz not null default now(),
  status text not null,
  colo text,
  country text,
  city text,
  region text,
  ip text
);

create index if not exists my_keepalive_logs_ping_time_idx
  on public.my_keepalive_logs (ping_time desc);

create table if not exists public.db2_keepalive_logs (
  id bigint generated by default as identity primary key,
  ping_time timestamptz not null default now(),
  status text not null,
  colo text,
  country text,
  city text,
  region text,
  ip text
);

create index if not exists db2_keepalive_logs_ping_time_idx
  on public.db2_keepalive_logs (ping_time desc);

alter table public.my_keepalive_logs enable row level security;
alter table public.db2_keepalive_logs enable row level security;

revoke all on table public.my_keepalive_logs from anon, authenticated;
revoke all on table public.db2_keepalive_logs from anon, authenticated;

grant select, insert, update, delete on table public.my_keepalive_logs to service_role;
grant select, insert, update, delete on table public.db2_keepalive_logs to service_role;
grant usage, select on all sequences in schema public to service_role;
